---
- name: Ip Address
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: "Debian11"
    clone_name: "{{vm_name}}Clone"
    group_name: "[{{clone_name}}]"
    max_retries: 10
    delay_seconds: 10
    output: ""
  tasks:
    #- name: Connecting to agent
    #  ansible.builtin.shell: "virsh connect qemu:///session"
      
    #- name: Wait for 40 seconds
     # pause:
      #  seconds: 40
    - name: libvirt
      virt:
#        hypervisor: qemu
        uri: qemu:///system
        state: running
        name: "{{clone_name}}"
      register: qemu_guest 
    - name: getting ip_address
 #     ansible.builtin.shell: "ip addr show dev enp1s0 | grep 'inet' | cut -d: -f2 | awk '{split($2, a, \"/\"); print a[1]}'"
      ansible.builtin.shell: "virsh domifaddr {{clone_name}} --source agent | grep -v 'lo:' | awk '/ipv4/ && /enp1s0/ {split($4, a, \"/\"); print a[1]}'"   
      register: ip_addr_result
      until: ip_addr_result.stdout | regex_search('\\d+\\.\\d+\\.\\d+\\.\\d+')
      retries: "{{ max_retries }}"
      delay: "{{ delay_seconds }}"
      ignore_errors: true
    - name: Extract IP address
      set_fact:
         output: "{{ ip_addr_result.stdout | regex_search('\\d+\\.\\d+\\.\\d+\\.\\d+') }}"
    - name: Adding group
      lineinfile:
        path: /etc/ansible/hosts
        line: "{{group_name}}\n{{output}}"
        insertafter: EOF


   
